name: Message on issue

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  workflow_call:

permissions: {}

jobs:
  script_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    name: Test
    steps:
      - uses: actions/checkout@v3
        with:
          # Check this repository out, otherwise the script won't be available,
          # as it checks out the repository where the workflow caller is located
          repository: jsnerdic/reusable-workflows
      - name: Test script
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/hello-world.js')
            await script({github, context, core})
