name: Message on issue

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  workflow_call:
    inputs:
      message:
        required: true
        type: string

permissions: {}

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Script output test
    outputs:
      lorem: ${{ steps.script.outputs.ipsum }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          # Check this repository out, otherwise the script won't be available,
          # as it checks out the repository where the workflow caller is located
          repository: jsnerdic/reusable-workflows
      - name: Test script
        id: script
        uses: actions/github-script@v7
        env:
          MESSAGE: ${{ inputs.message }}
        with:
          script: |
            const script = require('./.github/workflows/scripts/hello-world.js')
            await script({github, context, core})
  job2:
    runs-on: ubuntu-latest
    name: Script transfer test
    needs: job1
    steps:
      - run: echo "${{ needs.job1.outputs.lorem }}"
